# Spam Email Classifier

In [1]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv('email.csv')

In [8]:
data

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [10]:
# convert ham--> 1 , spam --0
data.loc[:,'class']=data.loc[:,'Category'].map({'ham':1,'spam':0})

In [26]:
data = data.dropna()

In [27]:
data.isnull().sum()

Message    0
class      0
dtype: int64

In [34]:
data.loc[5,'Message']

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"

In [22]:
data.isnull().sum()

Message    0
class      1
dtype: int64

In [23]:
data

                                                Message  class
0     Go until jurong point, crazy.. Available only ...    1.0
1                         Ok lar... Joking wif u oni...    1.0
2     Free entry in 2 a wkly comp to win FA Cup fina...    0.0
3     U dun say so early hor... U c already then say...    1.0
4     Nah I don't think he goes to usf, he lives aro...    1.0
...                                                 ...    ...
5568               Will ü b going to esplanade fr home?    1.0
5569  Pity, * was in mood for that. So...any other s...    1.0
5570  The guy did some bitching but I acted like i'd...    1.0
5571                         Rofl. Its true to its name    1.0
5572                                    isActive:false}    NaN

[5573 rows x 2 columns]

**Basic Data Cleaning**

In [35]:
import re
import string

In [36]:
def clean_text (text):
  text= text.lower()
  # remove html tags
  text = re.sub(r'<.*?>',"",text)
  # remove urls
  text = re.sub(r'http\S+|www\S+','',text)
  # remove emojis
  text = re.sub(r'[^x00-\x7F]+',' ',text)
  # special characters
  text = re.sub(r'[^a-z0-9\s]','',text)
  # white space
  text = re.sub(r'\s+',' ',text).strip()

  return text

In [40]:
data.loc[:,'cleaned_text']=data['Message'].apply(clean_text)

In [41]:
data

,Message,class,cleaned_text
0,"Go until jurong point, crazy.. Available only ...",1.0,go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,1.0,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,0.0,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,1.0,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",1.0,nah i don t think he goes to usf he lives arou...
...,...,...,...
5567,This is the 2nd time we have tried 2 contact u...,0.0,this is the 2nd time we have tried 2 contact u...
5568,Will ü b going to esplanade fr home?,1.0,will b going to esplanade fr home
5569,"Pity, * was in mood for that. So...any other s...",1.0,pity was in mood for that so any other suggest...
5570,The guy did some bitching but I acted like i'd...,1.0,the guy did some bitching but i acted like i d...
5571,Rofl. Its true to its name,1.0,rofl its true to its name

**Split data for x and y**

In [42]:
x = data['cleaned_text']
y= data['class']

**Split data for training and Testing**

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# Count Vectorizer

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_new_train = cv.fit_transform(x_train)
x_new_test = cv.transform(x_test)

In [ ]:
# fit_transform : Learn + transform
# transform : It just transforms

**Naive Bayes**

In [45]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_new_train,y_train)

MultinomialNB()

In [46]:
y_pred = model.predict(x_new_test)

In [48]:
# confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
confusion_matrix(y_test,y_pred)

array([[138,  11],
       [  0, 966]])

In [49]:
# accuracy
accuracy_score(y_test,y_pred)

0.9901345291479821

In [51]:
# recall
recall_score(y_test,y_pred)

1.0

In [52]:
_# precision
precision_score(y_test,y_pred)

0.9887410440122825

In [53]:
# f1
f1_score(y_test,y_pred)

0.9943386515697376

**Predictions**

In [54]:
msg = input("enter the message")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("Spam")
else:
  print("Ham")

enter the messageHello Good morning , we have team meeting at 1pm today
Ham

In [56]:
msg = input("enter the message")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("Spam")
else:
  print("Ham")

enter the messageHey you have won 10000m$ worth prize , congratulations
Spam

# TF-IDF

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x_train_tf = tf.fit_transform(x_train)
x_test_tf = tf.transform(x_test)

In [58]:
model = MultinomialNB()
model.fit(x_train_tf,y_train)
y_pred = model.predict(x_test_tf)

# Evaluate the model

In [59]:
confusion_matrix(y_test,y_pred)

array([[103,  46],
       [  0, 966]])

In [61]:
accuracy_score(y_test,y_pred)

0.9587443946188341

In [62]:
recall_score(y_test,y_pred)

1.0

In [64]:
precision_score(y_test,y_pred)

0.9545454545454546

In [65]:
f1_score(y_test,y_pred)

0.9767441860465116

In [66]:
msg = input("enter the message")
text = tf.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("Spam")
else:
  print("Ham")

enter the messageHello Good morning , we have team meeting at 1pm today
Ham

In [67]:
msg = input("enter the message: ")
text = tf.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("Spam")
else:
  print("Ham")

enter the message: Hey you have won 10000m$ worth prize , congratulations
Spam